binop_separator = "Back"
force_multiline_blocks = true
imports_granularity = "Crate"
match_block_trailing_comma = true
max_width = 100
merge_derives = true
spaces_around_ranges = true
unstable_features = true
use_small_heuristics = "Off"
